name: Docker Image CI

on:
  push:
    branches: [ "develop", "main" ]

jobs:
  build_and_push:
    name: Push new Image to Registry
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Registry login
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.REGISTRY_URL}}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Get current branch
      run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        file: Dockerfile
        push: true
        tags: '${{ secrets.REGISTRY_URL }}/chore-manager/${{ env.BRANCH }}:latest'

